services:
  - type: web
    name: GFC-RET-RETENCIONES
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    plan: starter
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER_EXTERNAL_URL
        value: https://gfc-ret-retenciones.onrender.com
